name: 🐛 Bug Report
description: Report a bug or unexpected behavior in the Conway's Game of Life app
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: component
    attributes:
      label: Component
      description: Which part of the app is affected?
      options:
        - label: iOS App (Game UI, board interaction)
        - label: Game Engine (Conway's Game logic)
        - label: Data Persistence (Core Data, board saving)
        - label: CLI Tool (ConwayCLI executable)
        - label: Build/Testing (Xcode project, tests)

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what's happening that shouldn't be happening
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Open the app
        2. Create a new board with dimensions...
        3. Add pattern...
        4. Press play...
        5. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: game-context
    attributes:
      label: Game Context
      description: Details about the game state when the bug occurred
      placeholder: |
        - Board dimensions: (e.g., 20x20)
        - Pattern used: (e.g., Glider, Random, Custom)
        - Generation number: (e.g., Generation 42)
        - Convergence state: (e.g., Still running, Extinct, Cyclical)
        - Auto-play speed: (e.g., Fast, Medium, Slow)

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this happen?
      options:
        - Always
        - Sometimes
        - Rarely
        - Only happened once
    validations:
      required: true

  - type: input
    id: ios-version
    attributes:
      label: iOS Version
      placeholder: "e.g., iOS 17.1"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: "e.g., iPhone 15 Pro, iPad Air, iOS Simulator"
    validations:
      required: true

  - type: input
    id: xcode-version
    attributes:
      label: Xcode Version (if building from source)
      placeholder: "e.g., Xcode 15.1"

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: |
        If applicable, add screenshots or screen recordings to help explain the problem.
        You can drag and drop images here.

  - type: textarea
    id: logs
    attributes:
      label: Console Logs/Error Messages
      description: |
        If you see any error messages in Xcode console or device logs, paste them here.
        Use triple backticks (```) to format code blocks.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant to this bug
      placeholder: Add any other context about the problem here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I can reproduce this issue consistently
          required: false